apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chat-app-api-ingress
  namespace: alex
spec:
  rules:
    - host: alex-react.duckdns.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chat-app-api-service
                port:
                  number: 80
